### ISSUE TITLE
Failed test on i386

### ISSUE THREAD

**Issue by remicollet** [phpv8/v8js#270] opened 2016-10-19 10:16 UTC
```
TEST 40/163 [tests/create_snapshot_basic.phpt]
========DIFF========
001+ ** ERROR: process timed out **
001- string(29) "snapshot successfully created"
002- int(46)
003- ===EOF===
========DONE========
FAIL Test V8Js::createSnapshot() : Basic snapshot creation & re-use [tests/create_snapshot_basic.phpt] 

TEST 114/163 [tests/memory_limit.phpt]
========DIFF========
001+ ** ERROR: process timed out **
001- V8JsMemoryLimitException
002- Script memory limit of 10000000 bytes exceeded
003- ===EOF===
========DONE========
FAIL Test V8::executeString() : Memory limit [tests/memory_limit.phpt] 

TEST 149/163 [tests/set_memory_limit_001.phpt]
========DIFF========
003+ 
004+  ** ERROR: process timed out **
003- V8JsMemoryLimitException
004- Script memory limit of 10000000 bytes exceeded
005- ===EOF===
========DONE========
FAIL Test V8::setMemoryLimit() : Memory limit applied to V8Function calls [tests/set_memory_limit_001.phpt] 

TEST 150/163 [tests/set_memory_limit_003.phpt]
========DIFF========
003+ 
004+  ** ERROR: process timed out **
003- V8JsMemoryLimitException
004- Script memory limit of 10000000 bytes exceeded
005- ===EOF===
========DONE========
FAIL Test V8::setMemoryLimit() : Memory limit can be imposed later [tests/set_memory_limit_003.phpt] 

TEST 151/163 [tests/set_memory_limit_basic.phpt]
========DIFF========
001+ ** ERROR: process timed out **
001- V8JsMemoryLimitException
002- Script memory limit of 10000000 bytes exceeded
003- ===EOF===
========DONE========
FAIL Test V8::setMemoryLimit() : Memory limit can be set on V8Js object [tests/set_memory_limit_basic.phpt] 

Number of tests :  163               160
Tests skipped   :    3 (  1.8%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    5 (  3.1%) (  3.1%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :  155 ( 95.1%) ( 96.9%)

```

**Comment by remicollet** [comment] 2016-10-19 10:21
FYI, build against v8-5.2.258-7.fc25 available in Fedora 25 repository.

**Comment by remicollet** [comment] 2016-10-19 11:23
I noticed, in v8js_timer_ctx, memory_limit should be size_t to match definition of total_heap_size (v8 HeapStatistics). But this doesn't seems to help.

**Comment by stesie** [comment] 2016-12-08 16:50
I installed a vagrant box with Fedora 25 today, to try this out (based on `vagrant init wholebits/fedora25-32; vagrant up --provider virtualbox`) ... so far I cannot make it work at all :-(

```
#
# Fatal error in ../src/snapshot/natives-external.cc, line 122
# Check failed: holder_.
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0xb67a38c5
 3: v8::internal::Heap::CreateInitialObjects()
 4: v8::internal::Heap::CreateHeapObjects()
 5: v8::internal::Isolate::Init(v8::internal::Deserializer*)
 6: v8::Isolate::New(v8::Isolate::CreateParams const&)
 7: 0xb69b700b
 8: dtrace_execute_internal
 9: 0x8037f56f
10: execute_ex
11: dtrace_execute_ex
12: zend_execute
13: zend_execute_scripts
14: php_execute_script
15: 0x80391f32
16: 0x8012dbb3
17: __libc_start_main
18: 0x8012de78
```

did you have to do anything special to get v8js to compile? So far I've just installed the v8 + v8-devel packages you mentioned + php-devel and compilers as needed

**Comment by remicollet** [comment] 2016-12-08 17:05
Nothing magic (version 1.3.3 with  https://github.com/phpv8/v8js/pull/266 applied)

Spec file : https://github.com/remicollet/remirepo/blob/master/php/pecl/php-pecl-v8js/php-pecl-v8js.spec
(the %build part should be quite easy to read)

**Comment by remicollet** [comment] 2016-12-09 09:09
If it can help, here is a scratch build of v1.3.2 in Fedora 25
http://koji.fedoraproject.org/koji/taskinfo?taskID=16804729

See the [i386 build.log](https://kojipkgs.fedoraproject.org//work/tasks/4731/16804731/build.log) and [x86_64 build.log](https://kojipkgs.fedoraproject.org//work/tasks/4730/16804730/build.log)

Notice, this task will be cleaned in a few days.

**Comment by stesie** [comment] 2017-03-12 09:17
Hey, finally had some time to re-visit this issue.  I don't have the box anymore, so I started over. This time everything worked fine (and v8js just picked up the needed snapshots -- which caused the trouble mentioned above).

I however cannot reproduce the test fails you mentioned (with current `php7` branch tip), the whole suite just passes (with three expected SKIPs)

Here are the versions I'm using (after all just current fedora 25 packages)

```
[vagrant@fedora25-32 build]$ rpm -qa | grep -e v8 -e ^php | sort
php-cli-7.0.16-1.fc25.i686
php-common-7.0.16-1.fc25.i686
php-devel-7.0.16-1.fc25.i686
php-json-7.0.16-1.fc25.i686
php-xml-7.0.16-1.fc25.i686
v8-5.2.258-7.fc25.i686
v8-devel-5.2.258-7.fc25.i686
```

So can you still reproduce this?

**Comment by remicollet** [comment] 2017-03-12 14:38
Indeed, everything is now OK.

```
SKIP Test V8Js::setModuleLoader : CommonJS modules [tests/commonjs_modules.phpt] 
SKIP Test V8::registerExtension() : Register extension with errors [tests/extensions_error.phpt] reason: too old V8 version
SKIP Test V8::executeString() : Check long 64-bit export from PHP to JS [tests/long_int64.phpt] reason: test not supported on 32bit PHP
SKIP Test V8::executeString() : DOM object passed from PHP [tests/object_dom.phpt] 
SKIP Test V8::executeString() : Pthreads test #1 [tests/pthreads_001.phpt] reason: pthreads extension required


=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   15
---------------------------------------------------------------------

Number of tests :  164               159
Tests skipped   :    5 (  3.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :  159 ( 97.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :    8 seconds
=====================================================================

```

**Comment by stesie** [comment] 2017-03-12 15:35
ok, good to know.  I'm closing it then.

Feel free to re-open (or create another issue) if you have more info

**Closed by stesie** 2017-03-12 15:35 UTC
