### ISSUE TITLE
Cant compile with php7.4 version

### ISSUE THREAD

**Issue by wiperawa** [phpv8/v8js#430] opened 2019-12-24 09:38 UTC
Trying to compile php7 branch for php7.4 version, but got this errors:
linux-um0w:/ # pecl install v8js
PHP Warning:  PHP Startup: v8js: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading v8js-2.1.1.tgz ...
Starting to download v8js-2.1.1.tgz (101,888 bytes)
.......................done: 101,888 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
Please provide the installation prefix of libv8 [autodetect] : /opt/v8

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in PEAR/Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/share/php7/PEAR/PEAR/Builder.php on line 407
building in /tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1
running: /tmp/pear/temp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js=/opt/v8
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib
checking for PHP extension directory... /usr/lib64/php7/extensions
checking for PHP installed headers prefix... /usr/include/php7
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking for V8 Javascript Engine... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for C standard version... c++11
checking how to allow c++11 narrowing... -Wno-narrowing
checking for libv8_libplatform... found
checking for V8 version... 7.5.288.23
checking for natives_blob.bin... found (/opt/v8/lib/natives_blob.bin)
checking for snapshot_blob.bin... found (/opt/v8/lib/snapshot_blob.bin)
checking for v8::ArrayBuffer::Allocator::NewDefaultAllocator... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/x86_64-suse-linux/bin/ld
checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/x86_64-suse-linux/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1/libtool --mode=compile g++ -Wno-narrowing -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1/include -I/tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1/main -I/tmp/pear/temp/v8js -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib -I/opt/v8/include -I/opt/v8  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/v8js/v8js_array_access.cc -o v8js_array_access.lo
libtool: compile:  g++ -Wno-narrowing -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1/include -I/tmp/pear/temp/pear-build-viper_workmyaH6l/v8js-2.1.1/main -I/tmp/pear/temp/v8js -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib -I/opt/v8/include -I/opt/v8 -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/v8js/v8js_array_access.cc  -fPIC -DPIC -o .libs/v8js_array_access.o
In file included from /usr/include/php7/Zend/zend_types.h:25,
                 from /usr/include/php7/Zend/zend.h:27,
                 from /usr/include/php7/main/php.h:33,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:42,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/usr/include/php7/Zend/zend_operators.h: In function ‘zend_long zend_dval_to_lval(double)’:
/tmp/pear/temp/v8js/php_v8js_macros.h:38:21: error: ‘std::std’ has not been declared
   38 | #define isfinite(a) std::isfinite(a)
      |                     ^~~
/usr/include/php7/Zend/zend_portability.h:323:52: note: in definition of macro ‘UNEXPECTED’
  323 | # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
      |                                                    ^~~~~~~~~
/usr/include/php7/main/../main/php_config.h:2342:26: note: in expansion of macro ‘isfinite’
 2342 | #define zend_finite std::isfinite
      |                          ^~~~~~~~
/usr/include/php7/Zend/zend_operators.h:110:18: note: in expansion of macro ‘zend_finite’
  110 |  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
      |                  ^~~~~~~~~~~
/tmp/pear/temp/v8js/php_v8js_macros.h:35:18: error: ‘std::std’ has not been declared
   35 | #define isnan(a) std::isnan(a)
      |                  ^~~
/usr/include/php7/Zend/zend_portability.h:323:52: note: in definition of macro ‘UNEXPECTED’
  323 | # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
      |                                                    ^~~~~~~~~
/usr/include/php7/main/../main/php_config.h:2340:25: note: in expansion of macro ‘isnan’
 2340 | #define zend_isnan std::isnan
      |                         ^~~~~
/usr/include/php7/Zend/zend_operators.h:110:48: note: in expansion of macro ‘zend_isnan’
  110 |  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
      |                                                ^~~~~~~~~~
/usr/include/php7/Zend/zend_operators.h: In function ‘zend_long zend_dval_to_lval_cap(double)’:
/tmp/pear/temp/v8js/php_v8js_macros.h:38:21: error: ‘std::std’ has not been declared
   38 | #define isfinite(a) std::isfinite(a)
      |                     ^~~
/usr/include/php7/Zend/zend_portability.h:323:52: note: in definition of macro ‘UNEXPECTED’
  323 | # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
      |                                                    ^~~~~~~~~
/usr/include/php7/main/../main/php_config.h:2342:26: note: in expansion of macro ‘isfinite’
 2342 | #define zend_finite std::isfinite
      |                          ^~~~~~~~
/usr/include/php7/Zend/zend_operators.h:121:18: note: in expansion of macro ‘zend_finite’
  121 |  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
      |                  ^~~~~~~~~~~
/tmp/pear/temp/v8js/php_v8js_macros.h:35:18: error: ‘std::std’ has not been declared
   35 | #define isnan(a) std::isnan(a)
      |                  ^~~
/usr/include/php7/Zend/zend_portability.h:323:52: note: in definition of macro ‘UNEXPECTED’
  323 | # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
      |                                                    ^~~~~~~~~
/usr/include/php7/main/../main/php_config.h:2340:25: note: in expansion of macro ‘isnan’
 2340 | #define zend_isnan std::isnan
      |                         ^~~~~
/usr/include/php7/Zend/zend_operators.h:121:48: note: in expansion of macro ‘zend_isnan’
  121 |  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
      |                                                ^~~~~~~~~~
In file included from /usr/include/dirent.h:245,
                 from /usr/include/php7/Zend/zend_virtual_cwd.h:91,
                 from /usr/include/php7/main/php.h:438,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:42,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/tmp/pear/temp/v8js/v8js_class.h: In function ‘v8js_ctx* v8js_ctx_fetch_object(zend_object*)’:
/tmp/pear/temp/v8js/v8js_class.h:83:54: warning: offsetof within non-standard-layout type ‘v8js_ctx’ is conditionally-supported [-Winvalid-offsetof]
   83 |  return (struct v8js_ctx *)((char *)obj - XtOffsetOf(struct v8js_ctx, std));
/tmp/pear/temp/v8js/v8js_class.h:83:43: note: in expansion of macro ‘XtOffsetOf’
   83 |  return (struct v8js_ctx *)((char *)obj - XtOffsetOf(struct v8js_ctx, std));
      |                                           ^~~~~~~~~~
/tmp/pear/temp/v8js/v8js_array_access.cc: In function ‘void v8js_array_access_enumerator(const v8::PropertyCallbackInfo<v8::Array>&)’:
/tmp/pear/temp/v8js/v8js_array_access.cc:213:43: warning: ‘v8::Local<v8::Context> v8::Isolate::GetEnteredContext()’ is deprecated: Use GetEnteredOrMicrotaskContext(). [-Wdeprecated-declarations]
  213 |    result->Set(isolate->GetEnteredContext(), i ++, V8JS_INT(j));
      |                                           ^
In file included from /opt/v8/include/v8-internal.h:14,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:7926:32: note: declared here
 7926 |                 Local<Context> GetEnteredContext());
      |                                ^~~~~~~~~~~~~~~~~
/opt/v8/include/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/tmp/pear/temp/v8js/v8js_array_access.cc:213:63: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
  213 |    result->Set(isolate->GetEnteredContext(), i ++, V8JS_INT(j));
      |                                                               ^
In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:3369:37: note: declared here
 3369 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/tmp/pear/temp/v8js/v8js_array_access.cc:217:41: warning: ‘v8::Local<v8::Context> v8::Isolate::GetEnteredContext()’ is deprecated: Use GetEnteredOrMicrotaskContext(). [-Wdeprecated-declarations]
  217 |  result->Set(isolate->GetEnteredContext(), V8JS_SYM("length"), V8JS_INT(i));
      |                                         ^
In file included from /opt/v8/include/v8-internal.h:14,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:7926:32: note: declared here
 7926 |                 Local<Context> GetEnteredContext());
      |                                ^~~~~~~~~~~~~~~~~
/opt/v8/include/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/tmp/pear/temp/v8js/v8js_array_access.cc:217:75: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
  217 |  result->Set(isolate->GetEnteredContext(), V8JS_SYM("length"), V8JS_INT(i));
      |                                                                           ^
In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:3364:37: note: declared here
 3364 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/tmp/pear/temp/v8js/v8js_array_access.cc: In function ‘void v8js_array_access_named_getter(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’:
/tmp/pear/temp/v8js/v8js_array_access.cc:248:54: warning: ‘v8::Local<v8::Context> v8::Isolate::GetEnteredContext()’ is deprecated: Use GetEnteredOrMicrotaskContext(). [-Wdeprecated-declarations]
  248 |   if(!prototype->ToObject(isolate->GetEnteredContext()).ToLocal(&prototype_object)) {
      |                                                      ^
In file included from /opt/v8/include/v8-internal.h:14,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:7926:32: note: declared here
 7926 |                 Local<Context> GetEnteredContext());
      |                                ^~~~~~~~~~~~~~~~~
/opt/v8/include/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/tmp/pear/temp/v8js/v8js_array_access.cc:253:52: warning: ‘v8::Local<v8::Context> v8::Isolate::GetEnteredContext()’ is deprecated: Use GetEnteredOrMicrotaskContext(). [-Wdeprecated-declarations]
  253 |   prototype_object->Get(isolate->GetEnteredContext(), property).ToLocal(&ret_value);
      |                                                    ^
In file included from /opt/v8/include/v8-internal.h:14,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:7926:32: note: declared here
 7926 |                 Local<Context> GetEnteredContext());
      |                                ^~~~~~~~~~~~~~~~~
/opt/v8/include/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/tmp/pear/temp/v8js/v8js_array_access.cc:253:72: warning: ignoring return value of ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const [with S = v8::Value; T = v8::Value]’, declared with attribute warn_unused_result [-Wunused-result]
  253 |   prototype_object->Get(isolate->GetEnteredContext(), property).ToLocal(&ret_value);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
make: *** [Makefile:206: v8js_array_access.lo] Ошибка 1
ERROR: `make' failed

**Comment by jakemercurio** [comment] 2020-01-03 19:10
This is probably a duplicate of issue https://github.com/phpv8/v8js/issues/409

I'm hitting the same error. I did make some progress by using this fork (which fixes a couple of the issues): https://github.com/derrekbertrand/v8js

A few tests are still failing though.

**Comment by HellLeaf** [comment] 2020-01-12 17:01
Same here, two test failed (using fork: https://github.com/derrekbertrand/v8js):
Test V8::executeString() : Testing lifespan of V8Js context objects [tests/ctx_lifetime.phpt]
Test V8::executeString() : Set property on function [tests/function_properties.phpt]

**Comment by derrekbertrand** [comment] 2020-01-28 01:09
All my branch does is mark a couple tests as skipped and beat a couple compiler errors with a wrench. I been meaning to sit down and debug it the rest of the way, but had to tend to other things at work.

I'll see if I can allocate time in the evenings to work out the rest of the issues.

**Comment by andriuspetrauskis** [comment] 2020-03-24 17:09
Hi, any update on this?

**Closed as completed** 2020-04-03 13:33 UTC

**Comment by murilolivorato** [comment] 2020-10-28 03:01
same problem , I cant install v8 in php 7.4
